### ISSUE TITLE
文档打算更新吗？

### ISSUE THREAD

**Issue by zz541843** [kotlin-orm/ktorm-docs#7]
文档看了很多遍，内容质量还算高的
内容应该很久没更新了吧，ktorm.v3的日志很多特性我都没看到文档有说明的
另外，如果打算重写文档的话，或许我可以帮一下，用vitepress

**Comment by vincentlauvlwj** [comment]
文档确实是该更新了，但现阶段我们更应该注重的是文档的内容，而不是修改前端的建站方案

**Comment by zz541843** [comment]
同步进行未尝不可，vitepress维护成本低，美观，而且迁移成本几乎为0，md文件直接能用，配个路由就行

**Comment by vincentlauvlwj** [comment]
人的精力是有限的，事情要有主次之分，先不改，完善内容即可，而且并没有看到改完之后有什么明显的收益

**Comment by zz541843** [comment]
> 人的精力是有限的，事情要有主次之分，先不改，完善内容即可，而且并没有看到改完之后有什么明显的收益

昨天我花了俩小时大概，弄好了，除了api那个页面不知道怎么来的，其他的都无成本迁移了，如果你需要的话，我可以上传
